@startuml
skinparam dpi 300
start
repeat
:**Wait for test candidate**
//state = idle//
//in.ready = true//
//out.valid = false//;

-> Receive valid input
in.valid = true;

:**Latch candidate**
//candidate = in//
//state = busy//
//in.ready = false//;

:**Set current node as root node**
//currentNode = treeROM(0)//;

-> Start tree traversal;

repeat
        if (**candidate.featureValue <= currentNode.thresholdValue**) then (true)
                :**Fetch left node**
                //currentNode = treeROM(currentNode.leftChildNodeAddress)//;
        else (false)
                :**Fetch right node**
                //currentNode = treeROM(currentNode.rightChildNodeAddress)//;
        endif
repeat while (**Is current node a leaf node**) is (no)
->yes;

:**Latch output to final classification given by leaf node**
//state = done//
//out = currentNode.class//
//out.valid = true//;

repeat while (**Wait until output is consumed**) is (Output consumed\n//out.ready = true//)
@enduml
